server:
  port: 8080

spring:
  thymeleaf:
   cache: false

  datasource:
    url: jdbc:mysql://rm-uf6431u6v7t3223q0bo.mysql.rds.aliyuncs.com:3306/employment?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useInformationSchema=true
    username: root
    password: XNXxnx520@

mybatis:
  mapper-locations: classpath*:mapper/*.xml
